#!/usr/bin/env python3
# encoding=UTF-8

# Copyright © 2016-2018 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

from lib import cli

if __name__ == '__main__':
    cli.main()

# vim:ts=4 sts=4 sw=4 et
